[main]
    ListenAddr  = "0.0.0.0"
    ListenPort  = 8899
    LogLevel = 4 # panic = 0, fatal = 1, error = 2, warning = 3, info = 4, debug = 5
	MaxMinDBPath = "../data/GeoLite2-Country.mmdb"
	FiftyOneDegreesDBPath = "../data/51Degrees-LiteV3.2.dat"